export const GET_ALL_CATEGORIES="GET_ALL_CATEGORIES";
export const CREATE_CATEGORY="CREATE_CATEGORY";

export const GET_ALL_FOODS="GET_ALL_FOODS";
export const CREATE_FOOD="CREATE_FOOD";

export const UPDATE_FOOD="UPDATE_FOOD";

export const GET_FOOD_BY_CATEGORY="GET_FOOD_BY_CATEGORY"