
export const GET_MY_RESTAURANT="GET_MY_RESTAURANT";
export const GET_RESTAURANT_BY_ID="GET_RESTAURANT_BY_ID";
export const CREATE_RESTAURANT="CREATE_RESTAURANT";
export const UPDATE_RESTAURANT_STATUS="UPDATE_RESTAURANT_STATUS";